APPBASE/Models/STOK/Product/ProductCRUD.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using APPBASE.Helpers;
using APPBASE.Models;
using APPBASE.Svcbiz;

namespace APPBASE.Models
{
    [Table("STO01PRODUCT")]
    public partial class Product : CRUD
    {
        public Byte? DTA_STS { get; set; }
        public string PROD_CODE { get; set; }
        public string PROD_NAME { get; set; }
        public string PROD_DESC { get; set; }
        public string PROD_IMAGE { get; set; }
        public int? PROD_QTY { get; set; }
        public decimal? PROD_PRICE_BASE { get; set; }
        public decimal? PROD_PRICE_SELL { get; set; }
        public DateTime? PROD_PRICEDT { get; set; }
        public Byte? PROD_STS { get; set; }
        public int? COUNTRY_ID { get; set; }
        public int? VENDOR_ID { get; set; }
        public int? PRODTYPE_ID { get; set; }
        public int? PRODSUBTYPE_ID { get; set; }
        public int? SERIAL_ID { get; set; }
        public int? FINISHING_ID { get; set; }
        public int? UKURAN_ID { get; set; }
        public int? UOM_ID { get; set; }
        public int? PRODNEW_ID { get; set; }
    } //End public partial class Product : CRUD
} //End namespace APPBASE.Models

APPBASE/Models/STOK/Product/ProductDS.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using APPBASE.Helpers;
using APPBASE.Models;
using APPBASE.Svcbiz;

namespace APPBASE.Models
{
    [Table("VWSTO01PRODUCT_INFO")]
    public partial class Product_info
    {
        public int? CREATEBY { get; set; }
        public int? UPDATEBY { get; set; }
        public DateTime? CREATEDT { get; set; }
        public DateTime? UPDATEDT { get; set; }
        [Key]
        public int? ID { get; set; }
        public Byte? DTA_STS { get; set; }
        public string PROD_CODE { get; set; }
        public string PROD_NAME { get; set; }
        public string PROD_DESC { get; set; }
        public string PROD_IMAGE { get; set; }
        public int? PROD_QTY { get; set; }
        public decimal? PROD_PRICE_BASE { get; set; }
        public decimal? PROD_PRICE_SELL { get; set; }
        public DateTime? PROD_PRICEDT { get; set; }
        public Byte? PROD_STS { get; set; }
        public int? COUNTRY_ID { get; set; }
        public int? VENDOR_ID { get; set; }
        public int? PRODTYPE_ID { get; set; }
        public int? PRODSUBTYPE_ID { get; set; }
        public int? SERIAL_ID { get; set; }
        public int? FINISHING_ID { get; set; }
        public int? UKURAN_ID { get; set; }
        public int? UOM_ID { get; set; }
        public int? PRODNEW_ID { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_NAME { get; set; }
        public string VENDOR_CODE { get; set; }
        public string VENDOR_NAME { get; set; }
        public string PRODTYPE_CODE { get; set; }
        public string PRODTYPE_NAME { get; set; }
        public string PRODSUBTYPE_CODE { get; set; }
        public string PRODSUBTYPE_NAME { get; set; }
        public string SERIAL_CODE { get; set; }
        public string SERIAL_NAME { get; set; }
        public string FINISHING_CODE { get; set; }
        public string FINISHING_NAME { get; set; }
        public string UKURAN_CODE { get; set; }
        public string UKURAN_NAME { get; set; }
        public string UOM_CODE { get; set; }
        public string UOM_DESC { get; set; }
        public string UOM_SYM { get; set; }
        public int? UOM_SEQNO { get; set; }
    } //End public partial class Product_info
} //End namespace APPBASE.Models

APPBASE/Controllers/STOK/Product/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APPBASE.Models;
using APPBASE.Helpers;
using APPBASE.Filters;
using APPBASE.Svcbiz;


namespace APPBASE.Controllers
{
    [MyActionFilterAttribute]
    public partial class ProductController : Controller
    {
        private DBMAINContext db = new DBMAINContext();
        //DS
        private ProductDS oDS = new ProductDS();
        private ProductnewDS oDSProductnew = new ProductnewDS();
        protected ProductDS oDSProduct = new ProductDS();
        protected ProductstockDS oDSProductstock = new ProductstockDS();
        protected VendorDS oDSVendor = new VendorDS();
        protected StorageDS oDSStorage = new StorageDS();
        //CRUD
        private ProductCRUD oCRUD = new ProductCRUD();
        private ProductstockCRUD oCRUDProductstock;
        protected TrnstockCRUD oCRUD_trn = new TrnstockCRUD();
        protected TrnstockdCRUD oCRUDDetail_trn = new TrnstockdCRUD();

        //Validation
        private Product_Validation oVAL;
        //BL
        protected Mutasi_newBL oBL;

        //Constructor 1
        public ProductController() {
            this.db = new DBMAINContext();
            //DS
            this.oDS = new ProductDS(db);
            this.oDSProductnew = new ProductnewDS();
            oCRUDProductstock = new ProductstockCRUD(this.db);
            //CRUD
            this.oCRUD = new ProductCRUD();
            this.oCRUDProductstock = new ProductstockCRUD();
            //BL
            this.oBL = new Mutasi_newBL(this.db);
        } //End Constructor
        //Constructor 2
        public ProductController(DBMAINContext poDB) {
            this.db = poDB;
            //DS
            this.oDS = new ProductDS();
            this.oDSProductnew = new ProductnewDS();
            oCRUDProductstock = new ProductstockCRUD(this.db);
            //CRUD
            this.oCRUD = new ProductCRUD();
            this.oCRUDProductstock = new ProductstockCRUD();
            //BL
            this.oBL = new Mutasi_newBL();
        } //End Constructor

        public ActionResult Index()
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_INDEX;
            var oData = oDS.getDatalist();
            if (oData != null) oData = oData.OrderByDescending(fld => fld.PROD_PRICEDT).ToList();
            return View(oData);
        }
        public ActionResult Indexvalidasi()
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_INDEX;
            if (hlpConfig.SessionInfo.getAppRoleId() != valFLAG.FLAG_ROLE_ADM) return RedirectToAction("Error403", "Error");
            ViewBag.CRUDSavedOrDelete = TempData["CRUDSavedOrDelete"];
            var oData = oDSProductnew.getDatalist_validate();
            if (oData != null) oData = oData.OrderByDescending(fld => fld.PRODNEW_OPENDT).ToList();
            return View(oData);
        }
        public ActionResult Details(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_DETAILS;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.VIEW;
            ViewBag.CRUDSavedOrDelete = TempData["CRUDSavedOrDelete"];

            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Create()
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_CREATE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.CREATE;
            return View();
        }
        public ActionResult Edit(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_UPDATE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.UPDATE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Edit_pricelist(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_UPDATE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.UPDATE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Delete(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_DELETE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.DELETE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    } //End public partial class ProductController : Controller
} //End namespace APPBASE.Controllers

APPBASE/Views/Product/Create.cshtml
@{
    ViewBag.Title = "Tambah Produk";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm())
{

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->
    
}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Product/Delete.cshtml
@model APPBASE.Models.ProductVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Hapus Produk";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm()) {
    Html.RenderPartial("_PartialConfirmDelete");

    <div class="box box-info">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            @{Html.RenderPartial("_Inputs");}
        </div><!-- /.box-body -->
        <div class="box-footer">
            <div class="row">
                <div class="col-xs-12">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div><!-- /.row -->
        </div><!-- /.box-footer -->
    </div><!-- /.box -->
}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Product/Details.cshtml
@using APPBASE.Helpers
@using APPBASE.Svcbiz

@{
    ViewBag.Title = "Informasi Produk";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@if (ViewBag.CRUDSavedOrDelete == valFLAG.FLAG_TRUE) {
      Html.RenderPartial("_PartialConfirmSaved"); 
}

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                @{Html.RenderPartial("_PartialButtonCRUD");}
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Product/Edit.cshtml
@model APPBASE.Models.ProductVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Ubah Produk";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm())
{

@Html.HiddenFor(model => model.ID)
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Product/Edit_pricelist.cshtml
@model APPBASE.Models.ProductVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Ubah Produk";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section includeBOTTOM {
    @Scripts.Render("~/bundles/JSInputMask")
}

@using (Html.BeginForm())
{

@Html.HiddenFor(model => model.ID)
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs_pricelist");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Product/Index.cshtml
@model IEnumerable<APPBASE.Models.ProductVM>
@using APPBASE.Helpers
@using APPBASE.Svcbiz
@using APPBASE.Svcutil

@{
    ViewBag.Title = "Info Produk";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{string vsClassBP_STS = "";}

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Action</th>
                    <th>
                        <div>Kode</div>
                        <div>barang</div>
                    </th>
                    <th>Nama Barang</th>
                    <th>Jumlah</th>
                    <th>Harga Pricelist</th>
                    <th>Foto</th>
                    <th>
                        <div>Tanggal</div>
                        <div>Update</div>
                    </th>
                </tr>
            </thead>

            <tbody>
                @if (Model == null) {
                    <tr>
                        <td colspan="2" align="center">@{Html.RenderPartial("_PartialEmpty");}</td>
                    </tr>
                }

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("Edit_pricelist", new { id = item.ID })" class="btn btn-flat btn-sm btn-success" style="margin-left:5px; color:White;"><i class="fa fa-edit"></i></a>
                        </td>
                        <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.PROD_CODE)</td>
                        <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.PROD_NAME)</td>
                        <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.PROD_QTY) @Html.DisplayFor(modelItem => item.UOM_DESC)</td>
                        <td class="SEARCHABLE_ROWS">@hlpConvertionAndFormating.ConvertDecimalToStringFmtThousand(item.PROD_PRICE_BASE)</td>
                        <td>
                            @if (item.PROD_IMAGE != null)
                            {
                                <img id="imgPROD_IMAGE" src="@Url.Content("~/")@Utility_FileUploadDownload.getImage_Product(item.PROD_IMAGE)" class="img-thumbnail img-wide-sm" alt="Foto" />
                            }
                            else
                            {
                                <img id="imgPROD_IMAGE" src="@Url.Content("~/")@Utility_FileUploadDownload.getImage_ProductNA()" class="img-thumbnail" alt="Foto" />
                            }
                        </td>
                        <td>@hlpConvertionAndFormating.ConvertDateToStringDateShortFmt(item.PROD_PRICEDT)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->

@section scripts {

<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/
        doSearchAbleTable('#searchValue', '', '.SEARCHABLE_ROWS');

        /*=========================================
        EVENTS
        =========================================*/
    });   //End $(document).ready
</script>

}

APPBASE/Views/Product/Indexvalidasi.cshtml
@using APPBASE.Helpers
@using APPBASE.Svcbiz

@{
    ViewBag.Title = "Validasi Produk Baru";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("Indexvalidasi", "Product", FormMethod.Post, new { id = "Validate_product" })) {

    <input type="hidden" id="ID" name="ID" value="@ViewBag.ID" />    
    <div class="box box-info">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div><!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            @{Html.RenderPartial("Indexvalidasi_data");}
        </div><!-- /.box-body -->
    </div><!-- /.box -->
}

<!-- Modal -->
<div class="modal fade" id="DialogConfirm" tabindex="-1" role="dialog" aria-labelledby="DialogConfirmTitle" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-aqua">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Konfirmasi</h4>
      </div>
      <div class="modal-body">
        <h1>Apakah data sudah benar?</h1>
      </div>
      <div class="modal-footer">
        <button type="submit" id="cmdConfirmYes" class="btn btn-flat btn-primary">Yes</button>
        <button type="button" id="cmdConfirmNo" class="btn btn-flat btn-danger">No</button>
        <button type="button" id="cmdConfirmCancel" class="btn btn-flat btn-warning" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>                        


@section scripts {

<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/
        doSearchAbleTable('#searchValue', '', '.SEARCHABLE_ROWS');
        var $linkID = $("#ID");
        /*=========================================
        EVENTS
        =========================================*/
        $(".cmdValidate").click(function () {
            $linkID.val("");
            var sID = $(this).attr("value");
            $linkID.val(sID);
            //$("#Validate_product").submit();
        })
        $("#cmdConfirmYes").click(function () {
            $("#Validate_product").submit();
        })
        $("#cmdConfirmNo").click(function () {
            window.location.replace("@Url.Content("~/")Productnew/Edit/" + $linkID.val());
        })
        $("#cmdConfirmCancel").click(function () {
            $linkID.val("");
        })

    });      //End $(document).ready
</script>

}

APPBASE/Views/Product/Indexvalidasi_data.cshtml
@model IEnumerable<APPBASE.Models.ProductnewVM>

@using APPBASE.Helpers
@using APPBASE.Svcbiz
@using APPBASE.Svcutil

@{Html.RenderPartial("_PartialConfirmValidated");}
@{Html.RenderPartial("_PartialConfirmValidateFailed");}
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                <div>Validasi</div>
                <div>Data</div>
            </th>
            <th>
                <div>Kode</div>
                <div>Barang</div>
            </th>
            <th>Nama Barang</th>
            <th>Jumlah</th>
            <th>Harga Pricelist</th>
            <th>Foto</th>
            <th>
                <div>Tanggal</div>
                <div>Barang</div>
                <div>Datang</div>
            </th>
            <th>Penyimpanan</th>
            <th>Keterangan</th>
        </tr>
    </thead>

    <tbody>
        @if (Model == null) {
            <tr>
                <td colspan="2" align="center">@{Html.RenderPartial("_PartialEmpty");}</td>
            </tr>
        }

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <button type="button" class="btn btn-primary btn-flat cmdValidate" data-toggle="modal" data-target="#DialogConfirm" value="@item.ID"><i class="fa fa-exchange"></i></button>
                </td>
                <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.PRODNEW_CODE)</td>
                <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.PRODNEW_NAME)</td>
                <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.PRODNEW_QTY) @Html.DisplayFor(modelItem => item.UOM_DESC)</td>
                <td class="SEARCHABLE_ROWS">@hlpConvertionAndFormating.ConvertDecimalToStringFmtThousand(item.PRODNEW_PRICE_BASE)</td>
                <td>
                    @if (item.PRODNEW_IMAGE != null)
                    {
                        <img id="imgPRODNEW_IMAGE" src="@Url.Content("~/")@Utility_FileUploadDownload.getImage_Product(item.PRODNEW_IMAGE)" class="img-thumbnail img-wide-sm" alt="Foto" />
                    }
                    else
                    {
                        <img id="imgPRODNEW_IMAGE" src="@Url.Content("~/")@Utility_FileUploadDownload.getImage_ProductNA()" class="img-thumbnail" alt="Foto" />
                    }
                </td>
                <td>@hlpConvertionAndFormating.ConvertDateToStringDateShortFmt(item.PRODNEW_OPENDT)</td>
                <td>@Html.DisplayFor(fld => item.STORAGE_NAME)</td>
                <td>@Html.DisplayFor(fld => item.PRODNEW_DESC)</td>
            </tr>
        }
    </tbody>
</table>

APPBASE/Views/Product/_Events.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/
        $("[data-mask]").inputmask(); //Optional if contains date field(s)
        inputDecimal();
//        if ($("#TRND_AMOUNTBASE_S").val() != "") {
//            formatNumberDecimal("#TRND_AMOUNTBASE_S");
//        } //End if ($("#TRND_AMOUNTBASE_S").val() != "")
//        
        $(".data-mask-decimal").each(function () {
            formatNumberDecimal("#" + this.id);
        });


        /*=========================================
        EVENTS
        =========================================*/
        $(".data-mask-decimal").focusout(function () {
            //alert($(this).attr("id"));
            formatNumberDecimal("#" + $(this).attr("id"));
        });


    });    //End $(document).ready
</script>