APPBASE/Models/STOK/CFG/Countrycode/CountrycodeCRUD.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using APPBASE.Helpers;
using APPBASE.Models;
using APPBASE.Svcbiz;

namespace APPBASE.Models
{
    [Table("STO01CFG_COUNTRYCODE")]
    public partial class Countrycode : CRUD
    {
        public int? ID { get; set; }
        public Byte? DTA_STS { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_NAME { get; set; }
    } //End public partial class Countrycode : CRUD
} //End namespace APPBASE.Models

APPBASE/Models/STOK/CFG/Countrycode/CountrycodeDS.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using APPBASE.Helpers;
using APPBASE.Models;
using APPBASE.Svcbiz;

namespace APPBASE.Models
{
    [Table("VWSTO01CFG_COUNTRYCODE_INFO")]
    public partial class Countrycode_info
    {
        public int? CREATEBY { get; set; }
        public int? UPDATEBY { get; set; }
        public DateTime? CREATEDT { get; set; }
        public DateTime? UPDATEDT { get; set; }
        [Key]
        public int? ID { get; set; }
        public Byte? DTA_STS { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_NAME { get; set; }
    } //End public partial class Countrycode_info
} //End namespace APPBASE.Models

APPBASE/Controllers/STOK/Countrycode/CountrycodeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APPBASE.Models;
using APPBASE.Helpers;
using APPBASE.Filters;
using APPBASE.Svcbiz;


namespace APPBASE.Controllers
{
    [MyActionFilterAttribute]
    public partial class CountrycodeController : Controller
    {
        private DBMAINContext db = new DBMAINContext();
        private CountrycodeDS oDS = new CountrycodeDS();
        private CountrycodeCRUD oCRUD = new CountrycodeCRUD();
        private Countrycode_Validation oVAL;

        public ActionResult Index()
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_INDEX;
            var oData = oDS.getDatalist();
            return View(oData);
        }
        public ActionResult Details(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_DETAILS;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.VIEW;
            ViewBag.CRUDSavedOrDelete = TempData["CRUDSavedOrDelete"];

            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Create()
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_CREATE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.CREATE;
            return View();
        }
        public ActionResult Edit(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_UPDATE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.UPDATE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Delete(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_DELETE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.DELETE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    } //End public partial class CountrycodeController : Controller
} //End namespace APPBASE.Controllers

APPBASE/Views/Countrycode/Create.cshtml
@{
    ViewBag.Title = "Kode Negara";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm())
{
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->
    
}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Countrycode/Delete.cshtml
@model APPBASE.Models.CountrycodeVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Kode Negara";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm()) {
    Html.RenderPartial("_PartialConfirmDelete");

    <div class="box box-info">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            @{Html.RenderPartial("_Inputs");}
        </div><!-- /.box-body -->
        <div class="box-footer">
            <div class="row">
                <div class="col-xs-12">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div><!-- /.row -->
        </div><!-- /.box-footer -->
    </div><!-- /.box -->
}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Countrycode/Details.cshtml
@using APPBASE.Helpers
@using APPBASE.Svcbiz

@{
    ViewBag.Title = "Kode Negara";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@if (ViewBag.CRUDSavedOrDelete == valFLAG.FLAG_TRUE) {
      Html.RenderPartial("_PartialConfirmSaved"); 
}

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                @{Html.RenderPartial("_PartialButtonCRUD");}
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Countrycode/Edit.cshtml
@model APPBASE.Models.CountrycodeVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Kode Negara";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm())
{

@Html.HiddenFor(model => model.ID)
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Countrycode/Index.cshtml
@model IEnumerable<APPBASE.Models.CountrycodeVM>
@using APPBASE.Helpers
@using APPBASE.Svcbiz

@{
    ViewBag.Title = "Kode Negara";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{string vsClassBP_STS = "";}

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="@Url.Action("Index", "Countrycode")">Kode Negara</a></li>
        <li ><a href="@Url.Action("Index", "Vendor")">Vendor</a></li>
        <li ><a href="@Url.Action("Index", "Prodtype")">Tipe Produk</a></li>
        <li ><a href="@Url.Action("Index", "Prodsubtype")">Jenis Produk</a></li>
        <li ><a href="@Url.Action("Index", "Serial")">Seri</a></li>
        <li ><a href="@Url.Action("Index", "Finishing")">Finishing</a></li>
        <li ><a href="@Url.Action("Index", "Ukuran")">Ukuran</a></li>
    </ul> <!-- ./nav nav-tabs -->

    <div class="tab-content">
        <div class="tab-pane active">

            <div class="input-group">
                <div class="input-group-btn">
                    <a href="@Url.Action("Create")" class="btn btn-flat btn-sm btn-success pull-right"><i class="fa fa-plus"></i> Tambah Data</a>
                </div>
            </div>


            @{Html.RenderPartial("Index_data");}
        </div> <!-- ./tab-pane active -->
    </div> <!-- ./tab-content -->

</div> <!-- ./nav-tabs-custom -->

@section scripts {

<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/
        doSearchAbleTable('#searchValue', '', '.SEARCHABLE_ROWS');

        /*=========================================
        EVENTS
        =========================================*/
    });   //End $(document).ready
</script>

}

APPBASE/Views/Countrycode/Index_data.cshtml
@model IEnumerable<APPBASE.Models.CountrycodeVM>
@using APPBASE.Helpers
@using APPBASE.Svcbiz

<div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Negara</th>
                    <th>Kode</th>
                </tr>
            </thead>

            <tbody>
                @if (Model == null) {
                    <tr>
                        <td colspan="3" align="center">@{Html.RenderPartial("_PartialEmpty");}</td>
                    </tr>
                }

                @{int nNo = 0;}

                @foreach (var item in Model)
                {
                    nNo++;
                    
                    <tr>
                        <td>@nNo</td>
                        <td class="SEARCHABLE_ROWS"><a href="@Url.Action("Details", new { id = item.ID })" class="btn btn-flat btn-sm btn-success"><i class="fa fa-search"></i></a> @Html.DisplayFor(modelItem => item.COUNTRY_NAME)</td>
                        <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.COUNTRY_CODE)</td>
                    </tr>
                }
            </tbody>
        </table>
</div> <!-- ./table-responsive -->

APPBASE/Views/Countrycode/_Events.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/
        $(".select2").select2();

        /*=========================================
        EVENTS
        =========================================*/

    }); //End $(document).ready
</script>

APPBASE/Views/Countrycode/_Inputs.cshtml
@model APPBASE.Models.CountrycodeVM
@using APPBASE.Helpers

@{string vsErrClass = "";}
@{string vsDisableButton = "";}
@{Boolean isShowDropdown = true;}
@{string vsReadonlyTextboxKey = "Readonly";}
@{string vsReadonlyTextbox = "";}
@if (ViewBag.CRUD_type == hlpFlags_CRUDOption.CREATE) { vsReadonlyTextboxKey = ""; }
@if ((ViewBag.CRUD_type == hlpFlags_CRUDOption.VIEW) || (ViewBag.CRUD_type == hlpFlags_CRUDOption.DELETE)) { vsDisableButton = "disabled"; vsReadonlyTextbox = "Readonly"; isShowDropdown = false; }
@{string vsDateFormat = "'alias': 'dd/mm/yyyy'";}

<div class="row">
    <div class="col-xs-12">
        @if (ViewData.ModelState["COUNTRY_CODE0"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="COUNTRY_CODE">Kode</label>
            <input type="text" id="COUNTRY_CODE" name="COUNTRY_CODE" value="@Html.DisplayFor(model => model.COUNTRY_CODE)" class="form-control" maxlength = "30" @vsReadonlyTextbox />

            @if (ViewData.ModelState["COUNTRY_CODE1"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("COUNTRY_CODE1")
                    </label>
            }
            @if (ViewData.ModelState["COUNTRY_CODE2"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("COUNTRY_CODE2")
                    </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->

<div class="row">
    <div class="col-xs-12">
        @if (ViewData.ModelState["COUNTRY_NAME0"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="COUNTRY_NAME">Kode Negara</label>
            <input type="text" id="COUNTRY_NAME" name="COUNTRY_NAME" value="@Html.DisplayFor(model => model.COUNTRY_NAME)" class="form-control" maxlength = "60" @vsReadonlyTextbox />

            @if (ViewData.ModelState["COUNTRY_NAME1"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("COUNTRY_NAME1")
                    </label>
            }
            @if (ViewData.ModelState["COUNTRY_NAME2"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("COUNTRY_NAME2")
                    </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->