APPBASE/Models/STOK/CFG/Prodtype/ProdtypeCRUD.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using APPBASE.Helpers;
using APPBASE.Models;
using APPBASE.Svcbiz;

namespace APPBASE.Models
{
    [Table("STO01CFG_PRODTYPE")]
    public partial class Prodtype : CRUD
    {
        public int? ID { get; set; }
        public Byte? DTA_STS { get; set; }
        public string PRODTYPE_CODE { get; set; }
        public string PRODTYPE_NAME { get; set; }
    } //End public partial class Prodtype : CRUD
} //End namespace APPBASE.Models

APPBASE/Models/STOK/CFG/Prodtype/ProdtypeDS.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using APPBASE.Helpers;
using APPBASE.Models;
using APPBASE.Svcbiz;

namespace APPBASE.Models
{
    [Table("VWSTO01CFG_PRODTYPE_INFO")]
    public partial class Prodtype_info
    {
        public int? CREATEBY { get; set; }
        public int? UPDATEBY { get; set; }
        public DateTime? CREATEDT { get; set; }
        public DateTime? UPDATEDT { get; set; }
        [Key]
        public int? ID { get; set; }
        public Byte? DTA_STS { get; set; }
        public string PRODTYPE_CODE { get; set; }
        public string PRODTYPE_NAME { get; set; }
    } //End public partial class Prodtype_info
} //End namespace APPBASE.Models

APPBASE/Controllers/STOK/Prodtype/ProdtypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APPBASE.Models;
using APPBASE.Helpers;
using APPBASE.Filters;
using APPBASE.Svcbiz;


namespace APPBASE.Controllers
{
    [MyActionFilterAttribute]
    public partial class ProdtypeController : Controller
    {
        private DBMAINContext db = new DBMAINContext();
        private ProdtypeDS oDS = new ProdtypeDS();
        private ProdtypeCRUD oCRUD = new ProdtypeCRUD();
        private Prodtype_Validation oVAL;

        public ActionResult Index()
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_INDEX;
            var oData = oDS.getDatalist();
            return View(oData);
        }
        public ActionResult Details(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_DETAILS;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.VIEW;
            ViewBag.CRUDSavedOrDelete = TempData["CRUDSavedOrDelete"];

            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Create()
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_CREATE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.CREATE;
            return View();
        }
        public ActionResult Edit(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_UPDATE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.UPDATE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Delete(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.MODULE_DELETE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.DELETE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    } //End public partial class ProdtypeController : Controller
} //End namespace APPBASE.Controllers

APPBASE/Views/Prodtype/Create.cshtml
@{
    ViewBag.Title = "Tipe Produk";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm())
{

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->
    
}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Prodtype/Delete.cshtml
@model APPBASE.Models.ProdtypeVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Tipe Produk";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm()) {
    Html.RenderPartial("_PartialConfirmDelete");

    <div class="box box-info">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            @{Html.RenderPartial("_Inputs");}
        </div><!-- /.box-body -->
        <div class="box-footer">
            <div class="row">
                <div class="col-xs-12">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div><!-- /.row -->
        </div><!-- /.box-footer -->
    </div><!-- /.box -->
}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Prodtype/Details.cshtml
@using APPBASE.Helpers
@using APPBASE.Svcbiz

@{
    ViewBag.Title = "Tipe Produk";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@if (ViewBag.CRUDSavedOrDelete == valFLAG.FLAG_TRUE) {
    Html.RenderPartial("_PartialConfirmSave" +
        "d");
}

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                @{Html.RenderPartial("_PartialButtonCRUD");}
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Prodtype/Edit.cshtml
@model APPBASE.Models.ProdtypeVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Tipe Produk";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm())
{

@Html.HiddenFor(model => model.ID)
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/Prodtype/Index.cshtml
@model IEnumerable<APPBASE.Models.ProdtypeVM>
@using APPBASE.Helpers
@using APPBASE.Svcbiz

@{
    ViewBag.Title = "Info Tipe Produk";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{string vsClassBP_STS = "";}

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li><a href="@Url.Action("Index", "Countrycode")">Kode Negara</a></li>
        <li ><a href="@Url.Action("Index", "Vendor")">Vendor</a></li>
        <li class="active"><a href="@Url.Action("Index", "Prodtype")">Tipe Produk</a></li>
        <li ><a href="@Url.Action("Index", "Prodsubtype")">Jenis Produk</a></li>
        <li ><a href="@Url.Action("Index", "Serial")">Seri</a></li>
        <li ><a href="@Url.Action("Index", "Finishing")">Finishing</a></li>
        <li ><a href="@Url.Action("Index", "Ukuran")">Ukuran</a></li>
    </ul> <!-- ./nav nav-tabs -->

    <div class="tab-content">
        <div class="tab-pane active">

            <div class="input-group">
                <div class="input-group-btn">
                    <a href="@Url.Action("Create")" class="btn btn-flat btn-sm btn-success pull-right"><i class="fa fa-plus"></i> Tambah Data</a>
                </div>
            </div>


            @{Html.RenderPartial("Index_data");}
        </div> <!-- ./tab-pane active -->
    </div> <!-- ./tab-content -->

</div> <!-- ./nav-tabs-custom -->

@section scripts {

<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/
        doSearchAbleTable('#searchValue', '', '.SEARCHABLE_ROWS');

        /*=========================================
        EVENTS
        =========================================*/
    });   //End $(document).ready
</script>

}

APPBASE/Views/Prodtype/Index_data.cshtml
@model IEnumerable<APPBASE.Models.ProdtypeVM>
@using APPBASE.Helpers
@using APPBASE.Svcbiz

<div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Tipe Produk</th>
                    <th>Kode</th>
                </tr>
            </thead>

            <tbody>
                @if (Model == null) {
                    <tr>
                        <td colspan="3" align="center">@{Html.RenderPartial("_PartialEmpty");}</td>
                    </tr>
                }

                @{int nNo = 0;}

                @foreach (var item in Model)
                {
                    nNo++;
                    
                    <tr>
                        <td>@nNo</td>
                        <td class="SEARCHABLE_ROWS"><a href="@Url.Action("Details", new { id = item.ID })" class="btn btn-flat btn-sm btn-success"><i class="fa fa-search"></i></a> @Html.DisplayFor(modelItem => item.PRODTYPE_NAME)</td>
                        <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.PRODTYPE_CODE)</td>
                    </tr>
                }
            </tbody>
        </table>
</div> <!-- ./table-responsive -->

APPBASE/Views/Prodtype/_Events.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/
        $(".select2").select2();

        /*=========================================
        EVENTS
        =========================================*/

    }); //End $(document).ready
</script>

APPBASE/Views/Prodtype/_Inputs.cshtml
@model APPBASE.Models.ProdtypeVM
@using APPBASE.Helpers

@{string vsErrClass = "";}
@{string vsDisableButton = "";}
@{Boolean isShowDropdown = true;}
@{string vsReadonlyTextboxKey = "Readonly";}
@{string vsReadonlyTextbox = "";}
@if (ViewBag.CRUD_type == hlpFlags_CRUDOption.CREATE) { vsReadonlyTextboxKey = ""; }
@if ((ViewBag.CRUD_type == hlpFlags_CRUDOption.VIEW) || (ViewBag.CRUD_type == hlpFlags_CRUDOption.DELETE)) { vsDisableButton = "disabled"; vsReadonlyTextbox = "Readonly"; isShowDropdown = false; }
@{string vsDateFormat = "'alias': 'dd/mm/yyyy'";}

<div class="row">
    <div class="col-xs-12">
        @if (ViewData.ModelState["PRODTYPE_CODE0"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="PRODTYPE_CODE">Kode</label>
            <input type="text" id="PRODTYPE_CODE" name="PRODTYPE_CODE" value="@Html.DisplayFor(model => model.PRODTYPE_CODE)" class="form-control" maxlength = "30" @vsReadonlyTextbox />

            @if (ViewData.ModelState["PRODTYPE_CODE1"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PRODTYPE_CODE1")
                    </label>
            }
            @if (ViewData.ModelState["PRODTYPE_CODE2"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PRODTYPE_CODE2")
                    </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->
<div class="row">
    <div class="col-xs-12">
        @if (ViewData.ModelState["PRODTYPE_NAME0"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="PRODTYPE_NAME">Tipe Produk</label>
            <input type="text" id="PRODTYPE_NAME" name="PRODTYPE_NAME" value="@Html.DisplayFor(model => model.PRODTYPE_NAME)" class="form-control" maxlength = "60" @vsReadonlyTextbox />

            @if (ViewData.ModelState["PRODTYPE_NAME1"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PRODTYPE_NAME1")
                    </label>
            }
            @if (ViewData.ModelState["PRODTYPE_NAME2"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PRODTYPE_NAME2")
                    </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->