APPBASE/Models/Accesscontrol/User/UserCRUD.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using APPBASE.Helpers;
using APPBASE.Models;
using APPBASE.Svcbiz;

namespace APPBASE.Models
{
    [Table("AC01USR")]
    public class User : CRUD
    {
        public Byte? DTA_STS { get; set; }
        public int? RES_ID { get; set; }
        public int? ROLE_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string EMAIL { get; set; }
        public int? USER_STS { get; set; }
        public string USER_IMG { get; set; }
        public int? BRANCH_ID { get; set; }
    } //End public class User : CRUD
} //End namespace APPBASE.Models

APPBASE/Models/Accesscontrol/User/UserDS.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using APPBASE.Helpers;
using APPBASE.Models;
using APPBASE.Svcbiz;

namespace APPBASE.Models
{
    [Table("VWAC01USR_INFO")]
    public class User_info
    {
        public int? CREATEBY { get; set; }
        public int? UPDATEBY { get; set; }
        public DateTime? CREATEDT { get; set; }
        public DateTime? UPDATEDT { get; set; }
        [Key]
        public int? ID { get; set; }
        public Byte? DTA_STS { get; set; }
        public int? RES_ID { get; set; }
        public int? ROLE_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string EMAIL { get; set; }
        public int? USER_STS { get; set; }
        public string USER_IMG { get; set; }
        public int? BRANCH_ID { get; set; }
        public int? MDLE_ID { get; set; }
        public string ROLE_CD { get; set; }
        public string ROLE_DISPLAY_NAME { get; set; }
    } //End public class User_info
} //End namespace APPBASE.Models

APPBASE/Controllers/User/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APPBASE.Models;
using APPBASE.Helpers;
using APPBASE.Filters;
using APPBASE.Svcbiz;

namespace APPBASE.Controllers
{
    [MyActionFilterAttribute]
    public partial class UserController : Controller
    {
        private DBMAINContext db = new DBMAINContext();
        private UserDS oDS = new UserDS();
        private UserCRUD oCRUD = new UserCRUD();
        private User_Validation oVAL;

        public int? ROLE_ID { get; set; }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            ViewBag.AC_MENU_ID = valMENU.HAKAKSES_USER_INDEX;

            var oData = oDS.getDatalist();
            return View(oData);
        }
        public ActionResult Details(int? id = null)
        {
            ViewBag.AC_MENU_ID = valMENU.HAKAKSES_USER_DETAILS;

            ViewBag.CRUD_type = hlpFlags_CRUDOption.VIEW;
            ViewBag.CRUDSavedOrDelete = TempData["CRUDSavedOrDelete"];

            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Create()
        {
            ViewBag.AC_MENU_ID = valMENU.HAKAKSES_USER_CREATE;

            ViewBag.CRUD_type = hlpFlags_CRUDOption.CREATE;
            return View();
        }
        public ActionResult Edit(int? id = null)
        {
            ViewBag.AC_MENU_ID = valMENU.HAKAKSES_USER_EDIT;

            ViewBag.CRUD_type = hlpFlags_CRUDOption.UPDATE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }
        public ActionResult Delete(int? id = null)
        {
            ViewBag.AC_MENU_ID = valMENU.HAKAKSES_USER_DELETE;

            ViewBag.CRUD_type = hlpFlags_CRUDOption.DELETE;
            var oData = oDS.getData(id);
            if (oData == null) { return HttpNotFound(); }
            return View(oData);
        }

        public ActionResult Activate(int? id = null)
        {
            ViewBag.AC_MENU_ID = valMENU.HAKAKSES_USER_CREATE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.VIEW;
            //var oData = oDS.getDataCPAR(id);
            //if (oData == null) { return HttpNotFound(); }
            //if (oData.BP_STS == valFLAG.FLAG_ACTIVE) { oData.BP_STS_NM = lblFIELD.USR_STS_ACTIVE; }
            //else { oData.BP_STS_NM = lblFIELD.USR_STS_INACTIVE; }

            //return View(oData);
            return View();
        }

        public ActionResult Changepassword(int? id = null)
        {
            //ViewBag.AC_MENU_ID = valMENU.HAKAKSES_USERHQ_EDIT;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.UPDATE;
            //var oData = oDS.getData(id);

            //if (oData == null) { return HttpNotFound(); }
            ViewBag.PREV_URL = Request.UrlReferrer;
            return View();
        }
        public ActionResult Deactivate(int? id = null)
        {
            ViewBag.AC_MENU_ID = valMENU.HAKAKSES_USER_DELETE;
            ViewBag.CRUD_type = hlpFlags_CRUDOption.VIEW;
            //var oData = oDS.getDataCPAR(id);
            //if (oData == null) { return HttpNotFound(); }
            //if (oData.BP_STS == valFLAG.FLAG_ACTIVE) { oData.BP_STS_NM = lblFIELD.USR_STS_ACTIVE; }
            //else { oData.BP_STS_NM = lblFIELD.USR_STS_INACTIVE; }

            //return View(oData);
            return View();
        }
    } //End public partial class UsercparController : Controller
} //End namespace APPBASE.Controllers

APPBASE/Views/User/Activate.cshtml
@{
    ViewBag.Title = "Unlock User Cabang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm()) {

    <div class="box box-success">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            @{Html.RenderPartial("_Inputs");}
        </div><!-- /.box-body -->
        <div class="box-footer">
            <div class="row">
                <div class="col-xs-12">
                    <button type="submit" class="btn btn-flat btn-success">Aktifkan User</button>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div><!-- /.row -->
        </div><!-- /.box-footer -->
    </div><!-- /.box -->
    
    
}

APPBASE/Views/User/Changepassword.cshtml
@model APPBASE.Models.UserdetailVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Ganti Password";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm())
{

    @Html.HiddenFor(model => model.ID)
    <div class="box box-info">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            @{Html.RenderPartial("Changepassword_");}
        </div><!-- /.box-body -->
        <div class="box-footer">
            <div class="row">
                <div class="col-xs-12">
                    <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div><!-- /.row -->
        </div><!-- /.box-footer -->
    </div><!-- /.box -->

}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

    <!-- Modal -->
    @{Html.RenderPartial("_Events");}

}

APPBASE/Views/User/Changepassword_.cshtml
@model APPBASE.Models.UserdetailVM
@using APPBASE.Helpers

@{string vsErrClass = "";}
@{string vsDisableButton = "";}
@{Boolean isShowDropdown = true;}
@{string vsReadonlyTextboxKey = "Readonly";}
@{string vsReadonlyTextbox = "";}
@if (ViewBag.CRUD_type == hlpFlags_CRUDOption.CREATE) { vsReadonlyTextboxKey = ""; }
@if ((ViewBag.CRUD_type == hlpFlags_CRUDOption.VIEW) || (ViewBag.CRUD_type == hlpFlags_CRUDOption.DELETE)) { vsDisableButton = "disabled"; vsReadonlyTextbox = "Readonly"; isShowDropdown = false; }
@{string vsDateFormat = "'alias': 'dd/mm/yyyy'";}

@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }))
{

    <input type="hidden" value="@ViewBag.PREV_URL" id="PREV_URL" name="PREV_URL" />
<div class="row">
    <div class="col-sm-12 col-md-6">
        @if (ViewData.ModelState["PASSWORD0"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="PASSWORD">Password lama</label>
            <input type="password" id="PASSWORD" name="PASSWORD" value="@Html.DisplayFor(model => model.PASSWORD)" class="form-control" @vsReadonlyTextbox />

            @if (ViewData.ModelState["PASSWORD1"] != null)
            {
                <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PASSWORD1")
                </label>
            }
            @if (ViewData.ModelState["PASSWORD2"] != null)
            {
                <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PASSWORD2")
                </label>
            }
            @if (ViewData.ModelState["PASSWORD3"] != null)
            {
                <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PASSWORD3")
                </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->
<div class="row">
    <div class="col-sm-12 col-md-6">
        @if (ViewData.ModelState["PASSWORD_NEW10"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="PASSWORD_NEW1">Password baru</label>
            <input type="password" id="PASSWORD_NEW1" name="PASSWORD_NEW1" value="@Html.DisplayFor(model => model.PASSWORD_NEW1)" class="form-control" @vsReadonlyTextbox />

            @if (ViewData.ModelState["PASSWORD_NEW11"] != null)
            {
                <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PASSWORD_NEW11")
                </label>
            }
            @if (ViewData.ModelState["PASSWORD_NEW3"] != null)
            {
                <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PASSWORD_NEW3")
                </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->
<div class="row">
    <div class="col-sm-12 col-md-6">
        @if (ViewData.ModelState["PASSWORD_NEW20"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="PASSWORD_NEW2">Password baru</label>
            <input type="password" id="PASSWORD_NEW2" name="PASSWORD_NEW2" value="@Html.DisplayFor(model => model.PASSWORD_NEW2)" class="form-control" @vsReadonlyTextbox />

            @if (ViewData.ModelState["PASSWORD_NEW21"] != null)
            {
                <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PASSWORD_NEW21")
                </label>
            }
            @if (ViewData.ModelState["PASSWORD_NEW3"] != null)
            {
                <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("PASSWORD_NEW3")
                </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->

}

APPBASE/Views/User/Create.cshtml
@{
    ViewBag.Title = "Tambah User Pusat";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm("Create", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->
    
}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/User/Deactivate.cshtml
@{
    ViewBag.Title = "Lock User Cabang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) {

    <div class="box box-danger">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            @{Html.RenderPartial("_Inputs");}
        </div><!-- /.box-body -->
        <div class="box-footer">
            <div class="row">
                <div class="col-xs-12">
                    <button type="submit" class="btn btn-flat btn-danger">Non Aktifkan User</button>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div><!-- /.row -->
        </div><!-- /.box-footer -->
    </div><!-- /.box -->
}

APPBASE/Views/User/Delete.cshtml
@model APPBASE.Models.UserdetailHQVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Hapus User Pusat";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm()) {
    Html.RenderPartial("_PartialConfirmDelete");

    <div class="box box-info">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            @{Html.RenderPartial("_Inputs");}
        </div><!-- /.box-body -->
        <div class="box-footer">
            <div class="row">
                <div class="col-xs-12">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div><!-- /.row -->
        </div><!-- /.box-footer -->
    </div><!-- /.box -->
}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/User/Details.cshtml
@using APPBASE.Helpers
@using APPBASE.Svcbiz

@{
    ViewBag.Title = "User Pusat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.CRUDSavedOrDelete == valFLAG.FLAG_TRUE) {
      Html.RenderPartial("_PartialConfirmSaved"); 
}

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                @{Html.RenderPartial("_PartialButtonCRUD");}
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/User/Edit.cshtml
@model APPBASE.Models.UserdetailHQVM
@using APPBASE.Helpers

@{
    ViewBag.Title = "Ubah User Pusat";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}

@using (Html.BeginForm("Edit", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

@Html.HiddenFor(model => model.ID)
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @{Html.RenderPartial("_Inputs");}
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-flat">Simpan Data</button>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-footer -->
</div><!-- /.box -->

}

<!-- Modal -->
@{Html.RenderPartial("_PartialDialogLookup");}


@section scripts {

<!-- Modal -->
@{Html.RenderPartial("_Events");}

}

APPBASE/Views/User/Index.cshtml
@model IEnumerable<APPBASE.Models.UserlistVM>
@using APPBASE.Helpers
@using APPBASE.Svcbiz

@{
    ViewBag.Title = "List User Kantor Pusat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{string vsClassBP_STS = "";}

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title"></h3>
        <div class="box-tools">
            <div class="input-group">
                <input type="text" id="searchValue" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Filter Data"/>
                <div class="input-group-btn">
                    <button class="btn btn-flat btn-sm btn-info"><i class="fa fa-search"></i></button>
                    <a href="@Url.Action("Create")" class="btn btn-flat btn-sm btn-warning" style="margin-left:5px; color:White;"><i class="fa fa-plus"></i> Tambah User</a>
                </div>
            </div>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Action</th>
                    <th>Deskripsi</th>
                </tr>
            </thead>

            <tbody>
                @if (Model == null) {
                    <tr>
                        <td colspan="2" align="center">@{Html.RenderPartial("_PartialEmpty");}</td>
                    </tr>
                }

                @foreach (var item in Model)
                {
                    
                    <tr>
                        <td>
                            <a href="@Url.Action("Details", new { id = item.ID })" class="btn btn-flat btn-sm btn-success" style="margin-left:5px; color:White;"><i class="fa fa-eye"></i> View Detail</a>
                        </td>
                        <td class="SEARCHABLE_ROWS">@Html.DisplayFor(modelItem => item.DISPLAY_NAME)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->

@section scripts {

<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/
        doSearchAbleTable('#searchValue', '', '.SEARCHABLE_ROWS');

        /*=========================================
        EVENTS
        =========================================*/
    });   //End $(document).ready
</script>

}

APPBASE/Views/User/_Events.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        /*=========================================
        INITIALIZE
        =========================================*/

        /*=========================================
        UPLOAD PHOTO USER_IMG
        =========================================*/
        $("#FileContainerUSER_IMG").hide(); //Optional if contains upload image field(s)
        $("#FileUSER_IMG").on('change', function () {
            previewImage(this, "#imgUSER_IMG");
        });
        $("#cmdUSER_IMG").click(function () {
            $("#FileUSER_IMG").click();
        }); //End  $("#cmdUSER_IMG").click

        /*=========================================
        EVENTS LOOKUP
        =========================================*/
        //Command LookUp [ROLE_ID]
        $("#cmdLookupROLE_ID").click(function () {
            var vaSearchValue = new Array();
            vaSearchValue[0] = "";
            //            vaSearchValue[1] = "Data array 2";
            //            vaSearchValue[2] = "Data array 3";
            var vaTargetTag = new Array();
            vaTargetTag[0] = 'ROLE_ID'; //ID
            vaTargetTag[1] = '';   //CD
            vaTargetTag[2] = 'ROLE_DISPLAY_NAME'; //DESC
            showLookup('Lookup/ShowRoleHQ', '', vaSearchValue, vaTargetTag);
        }); //End  $("#btnLookup").click
        //Command LookUp [RES_ID]
        $("#cmdLookupRES_ID").click(function () {
            var vaSearchValue = new Array();
            vaSearchValue[0] = "";
            //            vaSearchValue[1] = "Data array 2";
            //            vaSearchValue[2] = "Data array 3";
            var vaTargetTag = new Array();
            vaTargetTag[0] = 'RES_ID'; //ID
            vaTargetTag[1] = 'RES_NIP';   //CD
            vaTargetTag[2] = 'RES_NAME'; //DESC

            vaTargetTag[3] = 'JOBTITLE_DESC'; //DESC
            showLookup('Lookup/ShowEmployee', '', vaSearchValue, vaTargetTag);
        }); //End  $("#btnLookup").click

    }); //End $(document).ready
</script>

APPBASE/Views/User/_Inputs.cshtml
<div class="row">
    <div class="col-sm-12 col-md-4">
        @{Html.RenderPartial("_Inputs_Photo");}
    </div><!-- /.col (LEFT) -->

    <div class="col-sm-12 col-md-8">
        @{Html.RenderPartial("_Inputs_Name");}
    </div><!-- /.col (LEFT) -->
</div><!-- /.row -->

<hr />

@{Html.RenderPartial("_Inputs_Others");}

APPBASE/Views/User/_Inputs_Name.cshtml
@model APPBASE.Models.UserdetailHQVM
@using APPBASE.Helpers

@{string vsErrClass = "";}
@{string vsDisableButton = "";}
@{Boolean isShowDropdown = true;}
@{string vsReadonlyTextboxKey = "Readonly";}
@{string vsReadonlyTextbox = "";}
@if (ViewBag.CRUD_type == hlpFlags_CRUDOption.CREATE) { vsReadonlyTextboxKey = ""; }
@if ((ViewBag.CRUD_type == hlpFlags_CRUDOption.VIEW) || (ViewBag.CRUD_type == hlpFlags_CRUDOption.DELETE)) { vsDisableButton = "disabled"; vsReadonlyTextbox = "Readonly"; isShowDropdown = false; }
@{string vsDateFormat = "'alias': 'dd/mm/yyyy'";}


<div class="row">
    @Html.HiddenFor(model => model.RES_ID, new { id = "RES_ID" })
    <div class="col-xs-12">
        @if (ViewData.ModelState["RES_ID0"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="RES_NAME">Pilih Karyawan</label>


            <div class="input-group input-group-sm">
                <input type="text" id="RES_NAME" name="RES_NAME" value="@Html.DisplayFor(model => model.RES_NAME)" class="form-control" readonly />
                <span class="input-group-btn">
                    <button type="button" id="cmdLookupRES_ID" name="cmdLookupRES_ID" class="btn btn-info btn-flat" data-toggle="modal" data-target="#DialogLookup" @vsDisableButton><i class="fa fa-search"></i></button>
                </span>
            </div><!-- /input-group -->

            
            @if (ViewData.ModelState["RES_ID1"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("RES_ID1")
                    </label>
            }
            @if (ViewData.ModelState["RES_ID2"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("RES_ID2")
                    </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->
<div class="row">
    <div class="col-sm-12 col-md-6">
        @if (ViewData.ModelState["RES_NIP0"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="RES_NIP">Nomor Induk Karyawan</label>
            <input type="text" id="RES_NIP" name="RES_NIP" value="@Html.DisplayFor(model => model.RES_NIP)" class="form-control" maxlength = "20" readonly />

            @if (ViewData.ModelState["RES_NIP1"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("RES_NIP1")
                    </label>
            }
            @if (ViewData.ModelState["RES_NIP2"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("RES_NIP2")
                    </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
    <div class="col-sm-12 col-md-6">
        @if (ViewData.ModelState["JOBTITLE_DESC0"] != null) { vsErrClass = "has-error"; } else { vsErrClass = ""; }
        <div class="form-group @vsErrClass">
            <label for="JOBTITLE_DESC">Jabatan</label>
            <input type="text" id="JOBTITLE_DESC" name="JOBTITLE_DESC" value="@Html.DisplayFor(model => model.JOBTITLE_DESC)" class="form-control" maxlength = "30" readonly />

            @if (ViewData.ModelState["JOBTITLE_DESC1"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("JOBTITLE_DESC1")
                    </label>
            }
            @if (ViewData.ModelState["JOBTITLE_DESC2"] != null)
            {
                    <label class="control-label" for="inputError">
                    <i class="fa fa-times-circle-o"></i> @Html.ValidationMessage("JOBTITLE_DESC2")
                    </label>
            }
        </div> <!-- /.form-group -->
    </div> <!-- /.col-xs-12 -->
</div><!-- /.row -->